### PR TITLE
Properly trigger state updates whenever keys is updated

### PR DESCRIPTION
**Pull request by LoganDark**
It's only the polite thing to do.

I use this practice all the time, it's a perfectly safe and correct method.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Downstream users of useHotkeyState only get the updated `keys` the next time they render.

Issue Number: N/A

## What is the new behavior?
Downstream users of useHotkeyState get re-rendered immediately every time `keys` changes.

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

Components that call `useHotkeys` with an object that changes on every render will cause an infinite update loop.

## Other information
This change is for correctness, but it will require downstream components to pay more attention to how they use `useHotkeys`.

### CODE REVIEW

**Review by amcdnl — APPROVED** [review]

**Comment by LoganDark** [comment]
If this breaking change is to be published I'd like to replace `ref` in the public API with a straight HTMLElement reference

**Comment by LoganDark** [comment]
Also, this needs to be tested before publishing because I'm not sure if it'll cause an infinite loop anyway in `useHotkeys`

**Comment by amcdnl** [comment]
LOL - I already published. Can you give it a quick run? 1.2.4 is version

**Comment by LoganDark** [comment]
> LOL - I already published. Can you give it a quick run? 1.2.4 is version

It actually seems to work just like I thought. Any component in the entire app that calls `useHotkeys` without a `useMemo` instantly brings down the whole app. But as soon as that's resolved, everything is smooth sailing.

**Comment by amcdnl** [comment]
reverted and released - https://github.com/reaviz/reakeys/pull/10

**Comment by LoganDark** [comment]
Sorry about that. You should know by now I am a chronic "web ui committer"... xD

**Pull request merged**
