### PR TITLE
Use useMemo so that useEffects depending on hotkeys don't re-run unnecessarily

### PR DESCRIPTION
**Pull request by LoganDark**
## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
useHotkeys returns a new object every render even if nothing's changed

## What is the new behavior?
useHotkeys only returns a new object if the keys have changed

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

The PR actually fixes a useEffect that's causing performance issues in my app

## Other information

This should have been done from the start

### CODE REVIEW

**Comment by LoganDark** [comment]
@amcdnl please review

**Comment by amcdnl** [comment]
LGTM and thanks for your support!

**Comment by LoganDark** [comment]
This does still require consumers that *register* shortcuts to do `useHotkeys(useMemo(...))`, so that they don't get removed and re-added on every render, but once all that's said and done, the return value of `useHotkeys` should no longer be unstable in components that *read* from the already-registered shortcuts.

**Comment by amcdnl** [comment]
looks like you had a typo but i fixed it. 1.2.1 is released!

**Comment by amcdnl** [comment]
oh wait - so this is a breaking change?

**Comment by LoganDark** [comment]
> oh wait - so this is a breaking change?

No, it isn't. Consumers can continue using the library the same way they do now. It's just that since you recommend consumers use a non-memoized object, most components that call `useHotkeys` with an object will end up re-registering those hotkeys every render.

That's an easy fix in my codebase since I don't use any third-party components that depend on reakeys.

**Comment by LoganDark** [comment]
> looks like you had a typo but i fixed it. 1.2.1 is released!

Ah yeah I forgot that you have to pass a function as the first arg of useMemo, `() =>` is an easy fix

**Comment by amcdnl** [comment]
Got it - just wanted to confirm. There is a lot of other libraries that have similar code, im wondering how they deal w/ this? would you mind tweaking the docs?

**Comment by LoganDark** [comment]
> There is a lot of other libraries that have similar code, im wondering how they deal w/ this? would you mind tweaking the docs?

I can change some of the example code and add a section on why useMemo is important - would that be alright?

**Comment by amcdnl** [comment]
Yes please! That would be great!

**Pull request merged**
